package com.mx.ApiRestTienda.model;

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

//Mapeo de la tabla

/*
		 CREATE TABLE PRODUCTOS_PATITO(
    	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CODIGO_BARRA NUMBER NOT NULL,
    NOMBRE VARCHAR2(100)NOT NULL,
    PRECIO NUMBER NOT NULL,
    STOCK INT NOT NULL,
    CADUCIDAD DATE NOT NULL
	);
		  */
@Entity
@Table(name="PRODUCTOS_PATITO") 
@NoArgsConstructor//Constructor vacioo
@AllArgsConstructor//Constructor con parametros 
@Data//Encapsulamiento, to string 
public class Productos {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID",columnDefinition = "NUMBER",nullable = false)
	//Siempre parsear los tipos de datos primitivos si se aceptan o no valores nulos
	private Integer idProduct;
	@Column(name  = "CODIGO_BARRA",columnDefinition = "NUMBER",nullable = false)
	private Long codigoBarra;
	
	@Column(name = "NOMBRE",columnDefinition = "VARCHAR2(100)",nullable = false)
	private String nombre;
	
	@Column(name = "PRECIO",columnDefinition = "NUMBER",nullable = false)
	private Float precio;
	
	@Column(name = "STOCK",columnDefinition = "INT",nullable = false)
	private Integer stock;
	
	@Column(name = "CADUCIDAD",columnDefinition = "DATE",nullable = false)
	private Date caducidad;
	
	
}

























